### ISSUE TITLE
Getting error while currency converting

### ISSUE THREAD

**Issue by ansarikhurshid786** [arpitbatra123/CurrencyConverter#4]
I am new in android development. I clone this repository and fixed build issue.

Finally successfully installed in device. 

I am getting following issue while converting 
`W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.ResponseBody.string()' on a null object reference`

@arpitbatra123

**Comment by arpitbatra123** [comment]
I used the https://fixer.io/ API which now requires an API key. You can generate an API key and provide it while calling the API and it should work. I don't have an Android SDK setup at the moment but as soon as I do I'll push a fix for this. Thanks for using my Project!

**Comment by ansarikhurshid786** [comment]
how to add api key ? can you please help me

**Comment by arpitbatra123** [comment]
The API's endpoints have changed so I need to do some changes. Let me fix those and I'll get back to you.

**Comment by ansarikhurshid786** [comment]
Thanks @arpitbatra123

**Comment by arpitbatra123** [comment]
@ansarikhurshid786 I just pushed an update where I updated the dependencies and changed the layout and refactored code. I switched the API provider and you don't even need an API key now. Pull the changes / Reclone the repo and try again now.

**Comment by ansarikhurshid786** [comment]
Great, Thanks... working perfectly
